spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/backsns?characterEncoding=UTF-8&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true